version: '3.7'
services:
  mysql:
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
  php-fpm:
    build: dockers/php-fpm
    ports:
      - "9000:9001"
    volumes:
      - ./src:/var/www/src
    links:
      - mysql
    extra_hosts:
      - "docker-host.localhost:127.0.0.1"
  nginx:
    build: dockers/nginx
    ports:
      - "80:80"
    links:
      - php-fpm
    volumes:
      - ./src:/var/www/src
