main:
    path: /list/{userId}
    controller: App\UserInterface\Symfony\Controller\MainController::show
    methods: [GET]
    requirements:
        userId: '\d+'
tank_car:
    path: /tank
    controller: App\UserInterface\Symfony\Controller\FuelController::tank
    methods: [GET]
add_car:
    path: /car/add
    controller: App\UserInterface\Symfony\Controller\CarController::add
    methods: [GET]
remove_car:
    path: /car/remove
    controller: App\UserInterface\Symfony\Controller\CarController:remove
    methods: [GET]
