imports:
    - { resource: service/controller/tank.yaml }
    - { resource: service/repository.yaml }
    - { resource: service/url.yaml }
    - { resource: service/transaction.yaml }

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    App\:
        resource: '../../src/'
        exclude: '../../src/{Application/Command,Domain,Infrastructure/Information/Query}'
    App\Domain\Purchase\TankCarRepositoryInterface: '@App\Infrastructure\Purchase\Database\TankCarRepository'
    App\Domain\Information\CarQueryRepositoryInterface: '@App\Infrastructure\Information\Repository\CarQueryRepository'
