imports:
    - { resource: service/controller/tank.yaml }
    - { resource: service/repository.yaml }
    - { resource: service/url.yaml }
    - { resource: service/transaction.yaml }

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    App\:
        resource: '../../src/'
        exclude: '../../src/{Application/Command,Domain}'
    App\Domain\Purchase\TankCarRepositoryInterface: '@App\Infrastructure\Purchase\Database\TankCarRepository'
#    App\Infrastructure\:
#        resource: '../../src/Infrastructure'
#    App\Application\Query\:
#        resource: '../../src/Application/Query'
#    App\Application\Query\CarQueryInterface: 'App\Infrastructure\Query\CarQuery'
#    App\Application\Query\UserQueryInterface: 'App\Infrastructure\Query\UserQuery'
