imports:
    - { resource: service/controller/tank.yaml }
    - { resource: service/repository.yaml }
    - { resource: service/url.yaml }
    - { resource: service/transaction.yaml }

parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false
