version: '3.7'
services:
    nginx:
        build:
            context: nginx
        ports:
            - 80:80
        links:
            - php
        volumes:
            - ./../../application:/var/www/html
        container_name: infrastructure_nginx

    php:
        env_file:
            - ./../../.env
        build:
            context: php
        expose:
            - 9000
        links:
            - mysql
        volumes:
            - ./../../application:/var/www/html
        container_name: infrastructure_php

    mysql:
        environment:
            MYSQL_ROOT_PASSWORD: adJLJLdsa
        build:
            context: mysql
        expose:
          - 3306
        ports:
          - 9999:3306
        container_name: infrastructure_mysql
